import requests
import json
import os
import time

class BaseAgent:
    """Base class for all agents in the multi-agent system."""
    
    def __init__(self, agent_name):
        """
        Initialize an agent with a name.
        
        Args:
            agent_name (str): The name of the agent
        """
        self.name = agent_name
        self.model = "llama3.2:1b"
        self.ollama_url = "http://localhost:11434/api/generate"
        print(f"[AGENT] {self.name} initialized")
        
    def query_llm(self, prompt, max_retries=3, retry_delay=1):
        """
        Query the LLama model using Ollama API.
        
        Args:
            prompt (str): The prompt to send to the model
            max_retries (int): Maximum number of retries on failure
            retry_delay (int): Delay between retries in seconds
            
        Returns:
            str: The model's response
        """
        print(f"[AGENT] {self.name} querying LLM with prompt of length {len(prompt)} chars")
        
        # Add common system instructions based on agent type
        if "IntentClassifier" in self.__class__.__name__:
            system_context = """
            You are an intent classification system for a customer support chatbot.
            Remember:
            - Simple messages like "hello", "hi", "hey" are ALWAYS "greeting" intent with high confidence
            - Single-word greetings or very short greeting phrases must be classified as "greeting"
            - Messages that just say "I have a problem" or "I have an issue" without specific details must ALWAYS be classified as "casual" with high confidence
            - Messages that just say "I have a problem with X" without error messages or symptoms must be classified as "casual"
            - A message requires SPECIFIC details about a problem to be classified as an "issue"
            - Example of "casual": "I'm having trouble with my account"
            - Example of "casual": "I have an issue" or "I have a problem"
            - Example of "issue": "I'm getting error code 404 when trying to login with my credentials"
            - Be very strict in distinguishing between vague mentions of issues and specific support problems
            - Specific details include error codes, exact steps taken, specific symptoms, etc.
            - When in doubt between casual and issue, prefer casual for safety
            """
            prompt = f"{system_context}\n\n{prompt}"
        
        headers = {
            "Content-Type": "application/json"
        }
        
        data = {
            "model": self.model,
            "prompt": prompt,
            "stream": False
        }
        
        for attempt in range(max_retries):
            try:
                print(f"[AGENT] {self.name} LLM query attempt {attempt+1}/{max_retries}")
                response = requests.post(self.ollama_url, headers=headers, data=json.dumps(data))
                response.raise_for_status()
                result = response.json().get("response", "")
                print(f"[AGENT] {self.name} received response of length {len(result)} chars")
                return result
            except Exception as e:
                print(f"[AGENT] {self.name} LLM query error: {str(e)}")
                if attempt == max_retries - 1:
                    print(f"[AGENT] {self.name} all retry attempts failed")
                    return f"Error querying LLM: {str(e)}"
                else:
                    print(f"[AGENT] {self.name} retrying in {retry_delay} seconds...")
                    time.sleep(retry_delay)
    
    def log_activity(self, activity_type, input_data, output_data):
        """
        Log agent activity for monitoring and debugging.
        
        Args:
            activity_type (str): Type of activity (e.g., "summary", "recommendation")
            input_data (str): Input provided to the agent
            output_data (str): Output generated by the agent
        """
        # This is a simplified logging mechanism
        print(f"[AGENT] [{self.name}] {activity_type} - Input length: {len(input_data)} chars, Output length: {len(output_data)} chars")
        
        # In a production system, this would write to a database or log file
        
    def get_agent_info(self):
        """
        Get information about this agent.
        
        Returns:
            dict: Agent information including name and capabilities
        """
        return {
            "name": self.name,
            "model": self.model,
            "class": self.__class__.__name__
        }
